# Generated by Django 5.2.6 on 2025-09-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_article_tags_postuserlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True, unique=True),
        ),
    ]
